### ISSUE TITLE
✨Zodiac Chinesse 

### ISSUE THREAD

**Issue by Codelaby** [markbattistella/ZodiacKit#2]
Good job, it would be interesting to support Chinese zodiac signs, I have compiled some information to facilitate the implementation

## Zodiac Chinesse support

**How to Convert Dates Into Chinese Zodiacs in Swift**
https://betterprogramming.pub/how-to-convert-dates-into-chinese-zodiacs-30ed15e2f2a9

## Describe alternatives you've considered

Complementary with natural element (water, metal...)
https://www.purewow.com/wellness/chinese-zodiac-elements
https://www.chinahighlights.com/travelguide/chinese-zodiac/china-five-elements-philosophy.htm

**Comment by markbattistella** [comment]
Great idea! I'll look into it and see if I have the time to work it in :)
